# Generated by Django 4.1.7 on 2023-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('backdrop_path', models.CharField(max_length=200)),
                ('first_air_date', models.CharField(max_length=200)),
                ('genre_ids', models.IntegerField()),
                ('id', models.Field(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=200)),
                ('origin_name', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=300)),
                ('popularity', models.IntegerField()),
                ('poster_path', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
